targets:
  $default:
    builders:
      json_serializable:
        enabled: true
        options:
          explicit_to_json: true
          create_factory: true
          create_to_json: true
          field_rename: none
          include_if_null: false
          ignore_unannotated: false
          checked: false

      freezed:
        enabled: true
        options:
          immutable: true
          generate_to_string: true
          make_collections_unmodifiable: true
          union_key: "type"
          union_value_case: snake

      riverpod_generator:
        enabled: true
        options:
          provider_family_name_legacy: false

      slang_build_runner:
        enabled: true
        options:
          base_locale: en
          fallback_strategy: base_locale
          input_directory: assets/translations
          input_file_pattern: .i18n.json
          output_directory: lib/gen
          output_file_name: translations.g.dart
          output_format: single_file
          flutter_integration: true
          key_case: camel
          param_case: camel

      flutter_gen_runner:
        enabled: true
