if(EXISTS "${SOURCE1}")
    file(COPY "${SOURCE1}" DESTINATION "${DEST}")
    message(STATUS "Copied libcore.dll from runner directory")
elseif(EXISTS "${SOURCE2}")
    file(COPY "${SOURCE2}" DESTINATION "${DEST}")
    message(STATUS "Copied libcore.dll from libcore/bin directory")
else()
    message(STATUS "libcore.dll not found - will be copied during deployment")
endif()
